apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:10.6
          env:
            - name: MYSQL_DATABASE
              value: librenms
            - name: MYSQL_USER
              value: librenms
            - name: MYSQL_PASSWORD
              value: 1234567890
            - name: MYSQL_ROOT_PASSWORD
              value: ubnt123
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      volumes:
        - name: mysql-data
          emptyDir: {}
