apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librenms-data
  namespace: librenms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
